apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lubhatu83-go-gitops
  description: This is GitOps manifest for lubhatu83-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: lubhatu83-go
    backstage.io/kubernetes-id: lubhatu83-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: lubhatu83-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:lubhatu83-go
